### ISSUE TITLE
Implementação do seletor de escolha de Client S3 (e.g. s3fs, boto3)

### ISSUE THREAD

**Issue by anthonyvii27** [anthonyvii27/aws-goes16-api-wrapper#7]
## Description
Nesta feature, deve ser feita a implementação do método que definirá o seletor de escolha do Client S3. A princípio, podemos usar algum dos dois como "default", e caso este método não seja chamado, utilizar o padrão.

## Checklist
- [ ] Implementação do método
- [ ] Testes

**Comment by mateusrlopez** [comment]
O método escolhido para fazer a seleção de como será instanciado o client S3 foi implementada com sucesso, a partir do padrão Factory, cujo o qual temos uma classe responsável por fazer essa distinção passando para ela um parâmetro que diz respeito ao nome do client selecionado
