### ISSUE TITLE
Método para definição dos parâmetros de filtragem do NOAA GOES 16 (data inicial, data final, variável de dados (netCDF \data variable\) e produto)

### ISSUE THREAD

**Issue by anthonyvii27** [anthonyvii27/aws-goes16-api-wrapper#8]
## Description
Implementação do método para definição dos parâmetros de filtragem voltados ao NOAA GOES 16. Este método deve receber via parâmetro os atributos referentes aos parâmetros de filtragem. Os parâmetros são os seguintes:
- Data Inicial
- Data final
- Variável de dados (netCDF data variable)
- Produto
Pode ver a viabilidade de ter esse método para setar parâmetros default e, caso necessário, passar esses parâmetros no momento da listagem dos arquivos.

## Checklist
- [ ] Implementação do método
- [ ] Testes

**Comment by anthonyvii27** [comment]
## Description
Implementação do método para definição dos parâmetros de filtragem voltados ao NOAA GOES 16. Este método deve receber via parâmetro os atributos referentes aos parâmetros de filtragem. Os parâmetros são os seguintes:
- Data Inicial
- Data final
- Variável de dados (netCDF data variable)
- Produto
Pode ver a viabilidade de ter esse método para setar parâmetros default e, caso necessário, passar esses parâmetros no momento da listagem dos arquivos.

## Checklist
- [ ] Implementação do método
- [ ] Testes

**Comment by mateusrlopez** [comment]
Parâmetros adicionados a classe e setters definidos com sucesso
